### ISSUE TITLE
Real ?

### ISSUE THREAD

**Issue by johnnyAnd** [x0rz/EQGRP#3]
Where is the code showing hacking of Pakistan mobile system ???

**Comment by abdofarwanPro** [comment]
they say its real

**Comment by steelbrain** [comment]
Looks pretty real to me, [here](https://github.com/x0rz/EQGRP/blob/33810162273edda807363237ef7e7c5ece3e4100/Linux/doc/old/etc/user.mission.sicklestar.COMMON)'s a whole guide on how to hack Mobilink, which is apparently the largest telecom provider in Pakistan

**Comment by kalebealvs** [comment]
pretty legit... https://twitter.com/Snowden/status/850766326943690752
from snowden himself...

**Comment by johnnyAnd** [comment]
@steelbrain yes but we are inducing this from code only or there are actual dumps as well ?

**Comment by BustedSec** [comment]
This is just the decoded archive, stop asking stupid questions and start examining the code. Verified unaltered version.

**Comment by anastiel** [comment]
this working

**Comment by Tdog21** [comment]
To anyone in this thread if you can't run these binaries learn python (I'd suggest using crash course python as a starting language) since some of the most powerful binaries tend to be written in python.

**Comment by Tdog21** [comment]
or just get the fuck out of this repository

**Comment by NLDev** [comment]
@Tdog21 Sorry, but if someone is not capable of running / checking the files in this repository, this might not be the right place for them anyway.

**Comment by johnnyAnd** [comment]
@Tdog21  just asked if this repo has code or dump as well,  you dont need to put your ass in every matter, You can simply IGNORE stuff.
