### ISSUE TITLE
What‘s the progress of decryption?

### ISSUE THREAD

**Issue by WilliamGong** [x0rz/EQGRP#41]
I am just curious. I tried to decrypt by myself but I found that I couldn't find the private key. I only know the"unzip password" is "theequationgroup" , but I have no way to find more clues. Could anyone tell me the decrypting progress? Thanks.

**Comment by Zilverfire** [comment]
The password is (CrDj"(;Va.*NdlnzB9M?@K2)#>deB7mN) for this file bud as shown in the readme

**Comment by WilliamGong** [comment]
emmm...... But the encrypt method is GPG, Does it not need private key to decrypt? I don't know GPG well.  
Can the password in the readme calculate private key?

**Comment by Zilverfire** [comment]
That's the key for decryption. You would have best luck on a linux distro like centos or kali. 7zip may be capable of the extraction but i am unclear and don't have the time to test that. Its best to use these tools on linux anyways so you would not have to code an environment for it to run. There was a program that I originally used to open this file when it came out with the password and it could verify the archive with a signature file, I don't remember the name but it started with an R and sounded like a woman's name. Hope this helps

**Comment by WilliamGong** [comment]
Thank you. I thought it need decrypt by GnuPG directly.

**Comment by Zilverfire** [comment]
You can decrypt it with what whatever can handle the format. No unique, one-off software from one site. If you want you could probably do it in a vm.
