### ISSUE TITLE
Share the key?

### ISSUE THREAD

**Issue by alias1** [x0rz/EQGRP#5]
Is it possible to share the key used to decrypt (or is it somewhere here and I just haven't seen it?)

**Comment by rizend** [comment]
I think the password is `CrDj”(;Va.*NdlnzB9M?@K2)#>deB7mN` as posted at [https://medium.com/@shadowbrokerss/dont-forget-your-base-867d304a94b1](url)

**Comment by sonete** [comment]
CrD"(;Va.*NdlnzB9M?@K2)#>deB7mN
Copy paste from the web won't work as the double quotes (") is modified. Paste in text editor and retype the " character.

**Comment by Ekultek** [comment]
You guys don't actually believe this shit code was done by the nsa do you?

**Comment by pguillem** [comment]
Looks like my "warez" folder in 1997... 

Nsa my ass... it reads like a 16 trying to make a port scanner look dangerous .. :S

**Comment by thecircleoflifefree** [comment]
![avastblockreport](https://cloud.githubusercontent.com/assets/26904626/24834587/77bd1590-1ca7-11e7-9ed4-81f26b7ca0d4.jpg)

**Comment by Ekultek** [comment]
What's that suppose to prove?

**Comment by 0xCHERRY** [comment]
>  @pguillem
> Looks like my "warez" folder in 1997...
> Nsa my ass... it reads like a 16 trying to make a port scanner look dangerous .. :S

please kill yourself instantly

**Comment by 0xCHERRY** [comment]
> What's that suppose to prove?

AAAYYYYYYY

![ayyyyyyy](https://cloud.githubusercontent.com/assets/24250517/24836753/10880b60-1d14-11e7-8a59-bf0e8d77f10e.jpg)

**Comment by thecircleoflifefree** [comment]
It proves that you might need to disable/deactivate your firewall temporarily to avoid getting that notification and getting the file removed. I actually see now that the Readme.md file mentions this happening, which i hadn't seen yesterday. fyi on # 7 someone else also complained about this. 
It proves that i wanted to share some additional information and perhaps should have explained myself more from the beginning.

**Comment by Ekultek** [comment]
Okay that makes more sense lol

**Comment by leminski** [comment]
Passphrase for eqgrp-files-free?

**Comment by Tdog21** [comment]
I swear this repository has nothing but script kiddies in it

**Comment by tbodt** [comment]
this repository is where we learn that the nsa is just a bunch of script kiddies as we always thought

**Comment by doomguy** [comment]
@leminski Password for eqgrp-free-file.tar.xz.gpg is "theequationgroup" as stated in the original announcement.

**Comment by Ekultek** [comment]
Let me be the first to tell you, this wasn't written by the NSA.

**Comment by m1ck2** [comment]
Ha ha is it my notes you are trying to read. Lol that was Siri and Sam but Sam was using a code like some story book and representations.of it as places.

**Comment by Anonymous9172** [comment]
> I swear this repository has nothing but script kiddies in it

Thats why you found it.
